[tool.black]
line-length = 79

[tool.isort]
combine_as_imports = true
known_first_party = []
known_third_party = ['django', 'django_filters', 'rest_framework']
line_length = 79
profile = "black"
skip = "migrations, templates"
skip_gitignore = true
include_trailing_comma = true
force_grid_wrap = 0
multi_line_output = 3